apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentcar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentcar
  template:
    metadata:
      labels:
        app: rentcar
    spec:
      containers:
        - name: rentcar
          image: rentcar
          imagePullPolicy: Never
          ports:
            - containerPort: 8080